# Generated by Django 5.2.6 on 2025-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='defaultimg.png', upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='photos/rice.png', upload_to='product_images/'),
        ),
    ]
