# Generated by Django 5.2.6 on 2025-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0003_alter_category_image_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='defaultimg.png', upload_to='product_images/'),
        ),
    ]
